<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>no.rmz</groupId>
        <artifactId>rmatch-parent</artifactId>
        <version>1.9.4</version>
    </parent>

    <groupId>no.rmz</groupId>
    <artifactId>rmatch</artifactId>
    <version>1.9.4</version>
    <packaging>jar</packaging>

    <name>rmatch</name>
    <description>Fast Java multi-pattern regular expression matcher for large text corpora.</description>
    <url>https://github.com/la3lma/rmatch</url>
    <organization>
        <name>Rmz</name>
        <url>https://www.rmz.no/</url>
    </organization>

    <developers>
        <developer>
            <id>rmz</id>
            <name>Bjørn Remseth</name>
            <email>rmz@rmz.no</email>
        </developer>
    </developers>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy-agent</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-commons</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-engine</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-launcher</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <scm>
        <connection>scm:git:https://github.com/la3lma/rmatch.git</connection>
        <url>https://github.com/la3lma/rmatch</url>
        <developerConnection>scm:git:git@github.com:la3lma/rmatch.git</developerConnection>
        <tag>HEAD</tag>
    </scm>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>https://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${mavenSurefire.version}</version>
                <configuration>
                    <argLine>
                        -javaagent:${settings.localRepository}/net/bytebuddy/byte-buddy-agent/${byteBuddy.version}/byte-buddy-agent-${byteBuddy.version}.jar
                        -Xshare:off
                        --add-opens java.base/java.lang=ALL-UNNAMED
                        --add-opens java.base/java.util=ALL-UNNAMED
                    </argLine>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>${mavenSourcePlugin.version}</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <artifactId>maven-release-plugin</artifactId>
                <version>${mavenReleasePlugin.version}</version>
                <configuration>
                    <mavenExecutorId>forked-path</mavenExecutorId>
                </configuration>
            </plugin>


            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <configuration>
                    <doclint>none</doclint>
                    <sourceFileIncludes>
                        <sourceFileInclude>module-info.java</sourceFileInclude>
                        <sourceFileInclude>no/rmz/rmatch/*.java</sourceFileInclude>
                    </sourceFileIncludes>
                    <sourceFileExcludes>
                        <sourceFileExclude>no/rmz/rmatch/abstracts/**</sourceFileExclude>
                        <sourceFileExclude>no/rmz/rmatch/compiler/**</sourceFileExclude>
                        <sourceFileExclude>no/rmz/rmatch/engine/**</sourceFileExclude>
                        <sourceFileExclude>no/rmz/rmatch/impls/**</sourceFileExclude>
                        <sourceFileExclude>no/rmz/rmatch/interfaces/**</sourceFileExclude>
                        <sourceFileExclude>no/rmz/rmatch/internal/**</sourceFileExclude>
                        <sourceFileExclude>no/rmz/rmatch/utils/**</sourceFileExclude>
                    </sourceFileExcludes>
                </configuration>
            </plugin>

        </plugins>
    </build>
</project>
