services:
  postgres:
    image: postgres:15-alpine
    container_name: prospects_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: prospects_test
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5433:5432"  # Use non-standard port to avoid conflicts
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./data.sql:/docker-entrypoint-initdb.d/02-data.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d prospects_test"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local