/**
 * Copyright 2012. Bjørn Remseth (rmz@rmz.no).
 *
 * <p>Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License. You may obtain a copy of the License at
 *
 * <p>http://www.apache.org/licenses/LICENSE-2.0
 *
 * <p>Unless required by applicable law or agreed to in writing, software distributed under the
 * License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
 * express or implied. See the License for the specific language governing permissions and
 * limitations under the License.
 */
package no.rmz.rmatch.abstracts;

import static no.rmz.rmatch.internal.Checks.checkNotNull;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import no.rmz.rmatch.interfaces.AssertionEdge;
import no.rmz.rmatch.interfaces.MatchContext;
import no.rmz.rmatch.interfaces.NDFANode;
import no.rmz.rmatch.interfaces.Regexp;
import no.rmz.rmatch.interfaces.ZeroWidthAssertion;
import no.rmz.rmatch.utils.CounterType;
import no.rmz.rmatch.utils.FastCounter;
import no.rmz.rmatch.utils.FastCounters;

/**
 * Base implementation for nodes in rmatch's nondeterministic finite automata.
 *
 * <p>Subclasses provide the character-specific transition ({@link #getNextNDFA(Character)}). This
 * base class handles epsilon closure, assertion closure, node identity, terminal/failing flags, and
 * transition-cache bookkeeping.
 */
public abstract class AbstractNDFANode implements NDFANode {
  /**
   * Counts created NDFA nodes. The count is also used to allocate matcher-local node identifiers.
   */
  static final FastCounter COUNTER = FastCounters.newCounter(CounterType.ABSTRACT_NDFA_NODES);

  /** Counter for computed NDFA transition sets. */
  private static final FastCounter cachedEdgesCounter =
      FastCounters.newCounter(CounterType.CACHED_NDFA_EDGES);

  /** Cache of character transitions, including epsilon closure. */
  final ConcurrentHashMap<Character, SortedSet<NDFANode>> nextSetCache = new ConcurrentHashMap<>();

  /** Context-aware transition cache used only when zero-width assertions are present. */
  private final ConcurrentHashMap<ContextTransitionKey, SortedSet<NDFANode>> contextNextSetCache =
      new ConcurrentHashMap<>();

  /** Direct epsilon edges leaving this node. */
  private final SortedSet<NDFANode> epsilonSet = new TreeSet<>();

  /** Epsilon-like assertion edges going out of this node. */
  private final Collection<AssertionEdge> assertionEdges = new ArrayList<>();

  /** Expression that owns this node. */
  private final Regexp regexp;

  /** Whether this node is terminal for its owning expression. */
  private final boolean isTerminal;

  /** Whether reaching this node fails the current candidate. */
  private final boolean isFailing;

  /** Monitor used to synchronize access to single methods. */
  private final Object monitor = new Object();

  /** Matcher-local node identifier generated by a counter. */
  private final Long index;

  /**
   * Create an NDFA node.
   *
   * @param r expression that owns this node
   * @param isTerminal whether this node completes the expression
   * @param isFailing whether reaching this node fails the current candidate
   */
  protected AbstractNDFANode(final Regexp r, final boolean isTerminal, final boolean isFailing) {
    this.regexp = checkNotNull(r, "Regexp can't be null for an NDFA node");
    this.isTerminal = isTerminal;
    this.isFailing = isFailing;

    this.index = COUNTER.inc();

    if (isTerminal) {
      r.addTerminalNode(this);
    }
  }

  @Override
  public int hashCode() {
    return index.hashCode();
  }

  @Override
  public boolean equals(final Object o) {
    if (o instanceof AbstractNDFANode other) {
      return index.equals(other.index);
    } else {
      return false;
    }
  }

  /**
   * Create a non-failing NDFA node.
   *
   * @param r expression that owns this node
   * @param isTerminal whether this node completes the expression
   */
  protected AbstractNDFANode(final Regexp r, final boolean isTerminal) {
    this(r, isTerminal, false);
  }

  /**
   * Return this node's matcher-local identifier.
   *
   * @return node identifier
   */
  public final Long getId() {
    // This doesn't need to be locked, since it is immutable.
    return index;
  }

  @Override
  public final boolean isTerminal() {
    return isTerminal;
  }

  @Override
  public final Regexp getRegexp() {
    return regexp;
  }

  @Override
  public final boolean isActiveFor(final Regexp rexp) {
    return rexp.isActiveFor(this);
  }

  @Override
  public final boolean isTerminalFor(final Regexp rexp) {
    return rexp.hasTerminalNdfaNode(this);
  }

  @Override
  public final boolean isFailing() {
    return isFailing;
  }

  /**
   * Return every NDFA node reachable after consuming one character.
   *
   * <p>The returned set includes the direct character transition and all epsilon-closure nodes that
   * become reachable from it.
   *
   * @param ch character to consume
   * @return successor NDFA set used for DFA subset construction
   */
  @Override
  public final SortedSet<NDFANode> getNextSet(final Character ch) {
    return nextSetCache.computeIfAbsent(ch, this::getNextSetNonThreadsafe);
  }

  @Override
  public final SortedSet<NDFANode> getNextSet(final Character ch, final MatchContext context) {
    if (context == MatchContext.NONE) {
      return getNextSet(ch);
    }
    return contextNextSetCache.computeIfAbsent(
        new ContextTransitionKey(ch, context), key -> getNextSetNonThreadsafe(key.ch, key.context));
  }

  /**
   * Compute the successor set without using the transition cache.
   *
   * @param ch character to consume
   * @return successor NDFA set used for DFA subset construction
   */
  private SortedSet<NDFANode> getNextSetNonThreadsafe(final Character ch) {
    return getNextSetNonThreadsafe(ch, MatchContext.NONE);
  }

  private SortedSet<NDFANode> getNextSetNonThreadsafe(
      final Character ch, final MatchContext context) {

    // Eventually, the result we'll collect and return will go into this
    // set.
    final SortedSet<NDFANode> resultNodes = new TreeSet<>();

    // Meanwhile, we'll have a set of unexplored nodes that we'll have to
    // explore before we're done.
    final LifoSet<NDFANode> unexploredNodes = new LifoSet<>();

    // The set of unexplored nodes start with the current node.
    unexploredNodes.add(this);

    final Set<NDFANode> visitedNodes = new HashSet<>();

    while (!unexploredNodes.isEmpty()) {

      // Get the first NDFA node
      final NDFANode current = unexploredNodes.pop();
      visitedNodes.add(current);

      // By pursuing the current NDFA node through both
      // character-specific and epsilon edges, we get
      // a new NDFA node that is reachable through this character.
      // If we haven't explored this node, we add it to the
      // set of unexplored nodes.
      final NDFANode nextNode = current.getNextNDFA(ch);

      if (nextNode != null) {
        resultNodes.add(nextNode);
      }

      final Set<NDFANode> newNodes = extendByFollowingEpsilons(current, context);

      // Remove new nodes that are already in the resultNodes
      removeDuplicates(newNodes, resultNodes);

      if (!newNodes.isEmpty()) {
        newNodes.removeAll(visitedNodes);
        unexploredNodes.addAll(newNodes);
      }
    }

    followEpsilonLinks(resultNodes, context);

    // Updating the counter.
    cachedEdgesCounter.inc();

    // The set of NDFANode instances
    // representing the next DFA node.
    return resultNodes;
  }

  private static void removeDuplicates(
      final Set<NDFANode> newNodes, final SortedSet<NDFANode> resultNodes) {
    if (!newNodes.isEmpty() && !resultNodes.isEmpty()) {
      newNodes.removeAll(resultNodes);
    }
  }

  private Set<NDFANode> extendByFollowingEpsilons(
      final NDFANode current, final MatchContext context) {
    // Now we calculate a set difference between the  nodes
    // that can be reached from the current node through its
    // epsilons, and all the nodes we have already put into the
    // result set.   The difference is added to the
    // set of unexplored nodes.
    final Set<NDFANode> newNodes = new HashSet<>();
    final Set<NDFANode> epsilons = current.getEpsilons();
    if (!epsilons.isEmpty()) {
      newNodes.addAll(epsilons);
    }
    if (context != MatchContext.NONE) {
      for (final AssertionEdge edge : current.getAssertionEdges()) {
        if (edge.isSatisfiedBy(context, false)) {
          newNodes.add(edge.destination());
        }
      }
    }
    return newNodes;
  }

  /**
   * Then follow all epsilon links for the nodes in the resultNodes set (transitively reflexive
   * closure of epsilon links) and add all of those to the result set.
   */
  private static void followEpsilonLinks(
      final SortedSet<NDFANode> resultNodes, final MatchContext context) {

    final Set<NDFANode> epsilonClosure = new HashSet<>();
    for (final NDFANode r : resultNodes) {
      epsilonClosure.addAll(r.getEpsilons());
      if (context != MatchContext.NONE) {
        addSatisfiedAssertionDestinations(r, context, epsilonClosure);
      }
    }

    while (!epsilonClosure.isEmpty()) {
      final NDFANode next = epsilonClosure.iterator().next();
      if (resultNodes.add(next)) {
        epsilonClosure.addAll(next.getEpsilons());
        if (context != MatchContext.NONE) {
          addSatisfiedAssertionDestinations(next, context, epsilonClosure);
        }
      }
      epsilonClosure.remove(next);
    }
  }

  private static void addSatisfiedAssertionDestinations(
      final NDFANode node, final MatchContext context, final Set<NDFANode> destinations) {
    for (final AssertionEdge edge : node.getAssertionEdges()) {
      if (edge.isSatisfiedBy(context, true)) {
        destinations.add(edge.destination());
      }
    }
  }

  @Override
  public final SortedSet<NDFANode> getEpsilons() {
    synchronized (monitor) {
      return Collections.unmodifiableSortedSet(epsilonSet);
    }
  }

  @Override
  public final Collection<AssertionEdge> getAssertionEdges() {
    synchronized (monitor) {
      return List.copyOf(assertionEdges);
    }
  }

  @Override
  public final void addEpsilonEdge(final NDFANode n) {
    synchronized (monitor) {
      checkNotNull(n, "It is meaningless to add a NULL NDFANode " + "as an epsilon reachable node");
      epsilonSet.add(n);
    }
  }

  @Override
  public final void addAssertionEdge(final ZeroWidthAssertion assertion, final NDFANode n) {
    synchronized (monitor) {
      checkNotNull(assertion, "Assertion can't be null");
      checkNotNull(n, "Assertion edge destination can't be null");
      assertionEdges.add(new AssertionEdge(assertion, n));
    }
  }

  @Override
  public final void removeEpsilonReachableNode(final NDFANode n) {
    synchronized (monitor) {
      epsilonSet.remove(n);
    }
  }

  @Override
  public final int compareTo(final NDFANode t) {
    if (!(t instanceof AbstractNDFANode ta)) {
      throw new UnsupportedOperationException("Not supported yet.");
    } else {

      return index.compareTo(ta.index);
    }
  }

  private record ContextTransitionKey(Character ch, MatchContext context) {}
}
