name: CI
on:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [21]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Cache Maven repo
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build & install
        run: ./mvnw -q -B install

      - name: Macro test
        run: make bench-macro

## TODO: Enable these later
#      - name: Spotless check
#        run: ./mvnw -q -B spotless:check

#      - name: SpotBugs
#        run: ./mvnw -q -B spotbugs:check

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/target/site/**
            **/build/reports/**
