name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.REPORT_TOKEN || secrets.GITHUB_TOKEN }}
        issue-message: "Thank you so much for submitting an issue. Will look into it as soon as possible."
        pr-message: "Wow! Thank you so much for your first PR.  It's a big deal for me that you took the time to do this."
